apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-container-image
spec:
  entrypoint: buildkit-rootless-build-flow
  arguments:
    parameters:
    - name: model-version

  # Compatibility: some clusters ignore seccompProfile/appArmorProfile fields
  # (or enforce defaults) unless annotations are also set.
  podMetadata:
    annotations:
      seccomp.security.alpha.kubernetes.io/pod: unconfined
      container.apparmor.security.beta.kubernetes.io/main: unconfined

  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi

  volumes:
  - name: buildkitd
    emptyDir: {}
  - name: pip-cache
    emptyDir: {}

  templates:
  - name: buildkit-rootless-build-flow
    steps:
      - - name: clone-repo
          template: git-clone
      - - name: fetch-model
          template: download-model
          arguments:
            parameters:
            - name: model-version
              value: "{{workflow.parameters.model-version}}"
      - - name: buildkit-build
          template: buildkit-rootless
          arguments:
            parameters:
            - name: model-version
              value: "{{workflow.parameters.model-version}}"
      - - name: tag-model-staging
          template: set-mlflow-alias
          arguments:
            parameters:
            - name: model-version
              value: "{{workflow.parameters.model-version}}"
      - - name: deploy-to-staging
          template: trigger-deploy
          arguments:
            parameters:
            - name: model-version
              value: "{{workflow.parameters.model-version}}"
            - name: environment
              value: "staging"
      - - name: test-staging
          template: trigger-test
          arguments:
            parameters:
            - name: model-version
              value: "{{workflow.parameters.model-version}}"

  - name: git-clone
    retries:
      limit: 5
      retryPolicy: "Always"
      backoff:
        duration: "10s"
        factor: 2
    container:
      image: alpine/git:v2.26.2
      workingDir: /mnt/workspace
      env:
      - name: GIT_TERMINAL_PROMPT
        value: "0"
      command: [git]
      args:
        - clone
        - --depth
        - "1"
        - --filter=blob:none
        - --no-tags
        - --single-branch
        - --branch
        - workflow
        - https://github.com/teaching-on-testbeds/gourmetgram.git
        - .
      volumeMounts:
      - name: workdir
        mountPath: /mnt/workspace

  - name: download-model
    retries:
      limit: 5
      retryPolicy: "Always"
      backoff:
        duration: "10s"
        factor: 2
    inputs:
      parameters:
      - name: model-version
    container:
      image: python:3.11-slim
      env:
      - name: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"
      - name: PIP_CACHE_DIR
        value: /tmp/pip-cache
      command: [sh, -c]
      args:
        - |
          set -eu
          pip install mlflow-skinny==3.9.0
          export MLFLOW_TRACKING_URI=http://mlflow.gourmetgram-platform.svc.cluster.local:8000
          mkdir -p /tmp/mlflow_model

          echo "Downloading MLflow model artifacts..."
          mlflow artifacts download \
            --artifact-uri models:/GourmetGramFood11Model/{{inputs.parameters.model-version}} \
            -d /tmp/mlflow_model || { echo "MLflow download failed"; exit 1; }

          echo "Searching for model.pth..."
          FOUND=$(find /tmp/mlflow_model/data -name model.pth | head -n 1)
          if [ -z "$FOUND" ]; then
            echo "ERROR: model.pth not found in MLflow artifacts"; exit 1
          fi

          echo "Copying model.pth to app/ as food11.pth..."
          cp "$FOUND" /mnt/workspace/food11.pth
          echo "1.0.{{inputs.parameters.model-version}}" > /mnt/workspace/versions.txt
      volumeMounts:
      - name: workdir
        mountPath: /mnt/workspace
      - name: pip-cache
        mountPath: /tmp/pip-cache

  - name: buildkit-rootless
    retries:
      limit: 3
      retryPolicy: "Always"
      backoff:
        duration: "30s"
        factor: 2
    inputs:
      parameters:
      - name: model-version
    container:
      image: moby/buildkit:rootless
      env:
      - name: BUILDKITD_FLAGS
        value: --oci-worker-no-process-sandbox
      resources:
        requests:
          memory: "3Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
          cpu: "2"

      command: [buildctl-daemonless.sh]
      args:
        - build
        - --frontend
        - dockerfile.v0
        - --local
        - context=/mnt/workspace
        - --local
        - dockerfile=/mnt/workspace
        - --output
        - type=image,name=registry.kube-system.svc.cluster.local:5000/gourmetgram-app:staging-1.0.{{inputs.parameters.model-version}},push=true,registry.insecure=true
        - --export-cache
        - type=registry,ref=registry.kube-system.svc.cluster.local:5000/gourmetgram-app:buildcache,mode=max,registry.insecure=true
        - --import-cache
        - type=registry,ref=registry.kube-system.svc.cluster.local:5000/gourmetgram-app:buildcache,registry.insecure=true
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: Unconfined
        appArmorProfile:
          type: Unconfined
      volumeMounts:
      - name: workdir
        mountPath: /mnt/workspace
      - name: buildkitd
        mountPath: /home/user/.local/share/buildkit

  - name: set-mlflow-alias
    retries:
      limit: 5
      retryPolicy: "Always"
      backoff:
        duration: "10s"
        factor: 2
    inputs:
      parameters:
      - name: model-version
    script:
      image: python:3.11-slim
      command: [sh, -c]
      source: |
        export PIP_DISABLE_PIP_VERSION_CHECK=1
        export PIP_CACHE_DIR=/tmp/pip-cache
        pip install mlflow-skinny==3.9.0 > /dev/null
        export MLFLOW_TRACKING_URI=http://mlflow.gourmetgram-platform.svc.cluster.local:8000
        python -c "import mlflow; client = mlflow.tracking.MlflowClient(); client.set_registered_model_alias(name='GourmetGramFood11Model', alias='staging', version='{{inputs.parameters.model-version}}')"
      volumeMounts:
      - name: pip-cache
        mountPath: /tmp/pip-cache
  
  - name: trigger-deploy
    inputs:
      parameters:
      - name: model-version
      - name: environment
    resource:
      action: create
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          generateName: deploy-container-image-
        spec:
          workflowTemplateRef:
            name: deploy-container-image
          arguments:
            parameters:
            - name: environment
              value: "{{inputs.parameters.environment}}"
            - name: model-version
              value: "{{inputs.parameters.model-version}}"

  - name: trigger-test
    inputs:
      parameters:
      - name: model-version
    resource:
      action: create
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          generateName: test-staging-
        spec:
          workflowTemplateRef:
            name: test-staging
          arguments:
            parameters:
            - name: model-version
              value: "{{inputs.parameters.model-version}}"
