apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kaniko-training-build-
spec:
  entrypoint: kaniko-build-flow
  arguments:
    parameters:
    - name: branch
      value: mlops
  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

  templates:
  - name: kaniko-build-flow
    steps:
      - - name: clone-repo
          template: git-clone
          arguments:
            parameters:
            - name: branch
              value: "{{workflow.parameters.branch}}"
      - - name: kaniko-build
          template: kaniko

  - name: git-clone
    inputs:
      parameters:
      - name: branch
    container:
      image: alpine/git
      command: [sh, -c]
      args:
        - |
          set -eu
          git clone --branch "{{inputs.parameters.branch}}" https://github.com/teaching-on-testbeds/gourmetgram-train.git /mnt/workspace
      volumeMounts:
      - name: workdir
        mountPath: /mnt/workspace

  - name: kaniko
    container:
      image: gcr.io/kaniko-project/executor:latest
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
          cpu: "2"
      args:
        - --dockerfile=/mnt/workspace/Dockerfile
        - --context=/mnt/workspace
        - --destination=registry.kube-system.svc.cluster.local:5000/gourmetgram-train:latest
        - --insecure
      volumeMounts:
        - name: workdir
          mountPath: /mnt/workspace
